---
- name: Install all required packages
  apt:
    name:
      - debianutils
      - debootstrap
      - dracut
      - dracut-network
      - nfs-common
      - sed

- name: Install iSCSI packages
  apt:
    name:
      - open-iscsi
  when: xen_vman_iscsi_base_wwn is defined and xen_vman_iscsi_server is defined
