- name: Push vm configuration for {{ vm.host }} @{{ vm.org }}
  include_tasks: push_vm.yml

- name: Install vm {{ vm.host }} @{{ vm.org }} if needed
  include_tasks: install_system.yml
  when: not vm_config_file.stat.exists
