---
- include_tasks: install_packages.yml
- include_tasks: configure_xen.yml

- name: Collect all necessary facts and set them if needed
  include_tasks: set_facts.yml

- name: Install systemd service files
  include_tasks: systemd.yml

- name: Install all VMs
  include_tasks: install_all_vms.yml
  with_items: "{{ xen_vman_vms }}"
  loop_control:
    loop_var: vm
